version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: osmosis_blocks
      - name: osmosis_txs 
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: bronze_api
    schema: bronze_api
    tables: 
      - name: blockchain
  - name: bronze_streamline
    database: streamline
    schema: osmosis
    tables:
      - name: validator_metadata_api
      - name: asset_metadata_api
      - name: balances_api
      - name: pool_balances_api
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'OSMOSIS' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'OSMOSIS' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: address_labels
      - name: address_tags
      - name: dim_dates
      - name: dim_date_hours
  - name: axelar_silver
    database: "{{ 'axelar' if target.database == 'OSMOSIS' else 'axelar_dev' }}"
    schema: silver
    tables:
      - name: link_events
      - name: transfers
