version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: osmosis_blocks
      - name: osmosis_txs 
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: shared2 
    database: flipside_prod_db 
    schema: redshift
    tables: 
      - name: hours
  - name: bronze_api
    schema: bronze_api
    tables: 
      - name: blockchain
  - name: bronze_streamline
    database: streamline
    schema: osmosis
    tables:
      - name: validator_metadata_api
      - name: asset_metadata_api
      - name: balances_api
      - name: pool_balances_api