version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: osmosis_blocks
      - name: osmosis_txs 
  - name: crosschain_bronze
    database: "{{ 'crosschain' if target.database == 'OSMOSIS' else 'crosschain_dev' }}"
    schema: bronze
    tables:
      - name: legacy_prices
  - name: bronze_api
    schema: bronze_api
    tables: 
      - name: blockchain
      - name: manual_tx_lq
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "OSMOSIS_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "OSMOSIS" }}
    tables:
      - name: validator_metadata_api
      - name: asset_metadata_api
      - name: balances_api
      - name: pool_balances_api
      - name: blocks
      - name: transactions
      - name: txcount
      - name: tx_search
      - name: pool_balances
      - name: balances
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'OSMOSIS' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: asset_metadata_coin_market_cap
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: hourly_prices_coin_gecko
      - name: number_sequence
      - name: labels_combined
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'OSMOSIS' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
      - name: dim_tags
      - name: dim_dates
      - name: dim_date_hours
  - name: axelar_silver
    database: "{{ 'axelar' if target.database == 'OSMOSIS' else 'axelar_dev' }}"
    schema: silver
    tables:
      - name: link_events
      - name: transfers
  - name: bronze
    schema: bronze
    tables:
      - name: chainwalkers_txs
      - name: manual_large_txs
  - name: github_actions
    database: osmosis
    schema: github_actions
    tables:
      - name: workflows