version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: osmosis_blocks
      - name: osmosis_txs 
  - name: shared
    database: flipside_prod_db
    schema: silver
    tables:
      - name: prices_v2
  - name: shared2 
    database: flipside_prod_db 
    schema: redshift
    tables: 
      - name: hours
  - name: osmosis_external
    schema: bronze
    loader: S3
    tables:
      - name: validator_metadata_api
        description: "External table of osmosis validator metadata files"
        external:
          location: "@osmosis.bronze.analytics_external_tables/{{target.database}}/VALIDATOR_METADATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
        columns:
          - name: rank
            data_type: number
            description: ""
            expression: value:rank::number
          - name: account_address
            data_type: string
            description: ""
            expression: value:account_address::string
          - name: operator_address
            data_type: string
            description: ""
            expression: value:operator_address::string
          - name: consensus_pubkey
            data_type: string
            description: ""
            expression: value:consensus_pubkey::string
          - name: jailed
            data_type: boolean
            description: ""
            expression: value:jailed::boolean
          - name: status
            data_type: number
            description: ""
            expression: value:status::number
          - name: tokens
            data_type: number
            description: ""
            expression: value:tokens::number
          - name: delegator_shares
            data_type: float
            description: ""
            expression: value:delegator_shares::float
          - name: moniker
            data_type: string
            description: ""
            expression: value:moniker::string
          - name: identity
            data_type: string
            description: ""
            expression: value:identity::string
          - name: website
            data_type: string
            description: ""
            expression: value:website::string
          - name: details
            data_type: string
            description: ""
            expression: value:details::string
          - name: unbonding_height
            data_type: number
            description: ""
            expression: value:unbonding_height::number
          - name: unbonding_time
            data_type: timestamp_ntz
            description: ""
            expression: value:unbonding_time::string::timestamp_ntz
          - name: rate
            data_type: float
            description: ""
            expression: value:rate::float
          - name: max_rate
            data_type: float
            description: ""
            expression: value:max_rate::float
          - name: max_change_rate
            data_type: float
            description: ""
            expression: value:max_change_rate::float
          - name: uptime
            data_type: variant
            description: ""
            expression: value:update::variant
            # (1-(value:uptime:missed::number/value:uptime:over_blocks::number))
          - name: min_self_delegation
            data_type: number
            description: ""
            expression: value:min_self_delegation::number
      - name: asset_metadata_api
        description: "External table of osmosis asset metadata files"
        external:
          location: "@osmosis.bronze.analytics_external_tables/{{target.database}}/ASSET_METADATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
        columns:
          - name: base
            data_type: string
            description: ""
            expression: value:base::string
          - name: coingecko_id
            data_type: string
            description: ""
            expression: value:coingecko_id::string
          - name: denom_units
            data_type: array
            description: ""
            expression: value:denom_units::array
          - name: description
            data_type: string
            description: ""
            expression: "value:description::string"
          - name: ibc
            data_type: variant
            description: ""
            expression: value:ibc::variant
          - name: name
            data_type: string
            description: ""
            expression: value:name::string
          - name: symbol
            data_type: string
            description: ""
            expression: value:symbol::string
      - name: balances_api
        description: "Wallet balances from osmosis api"
        external:
          location: "@osmosis.bronze.analytics_external_tables/OSMOSIS/BALANCES_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true
          partitions:
            - name: _inserted_date
              data_type: string
              expression: substr((split_part(METADATA$FILENAME,'/',3)),16,10)
        columns:
          - name: block_id
            data_type: number
            description: ""
          - name: address
            data_type: string
            description: ""
          - name: balances
            data_type: array
            description: ""